// data-mu1990.js
export const MU1990_DATA = {
    name: "Marvel Universe 1990",
    maxCount: 167,
    baseCards: [
        { n: 1, name: "Captain America" },
        { n: 2, name: "Spider-Man" },
        { n: 3, name: "The Hulk" },
        { n: 4, name: "Daredevil" },
        { n: 5, name: "Nick Fury" },
        { n: 6, name: "The Thing" },
        { n: 7, name: "Professor X" },
        { n: 8, name: "Cyclops" },
        { n: 9, name: "Marvel Girl" },
        { n: 10, name: "Wolverine" },
        { n: 11, name: "Phoenix" },
        { n: 12, name: "Power Man" },
        { n: 13, name: "Dazzler" },
        { n: 14, name: "Dagger" },
        { n: 15, name: "Quasar" },
        { n: 16, name: "Sub-Mariner" },
        { n: 17, name: "Hulk (Gray)" },
        { n: 18, name: "Thor" },
        { n: 19, name: "Mister Fantastic" },
        { n: 20, name: "Black Panther" },
        { n: 21, name: "Archangel" },
        { n: 22, name: "Iceman" },
        { n: 23, name: "Wolverine" },
        { n: 24, name: "Storm" },
        { n: 25, name: "Shadowcat" },
        { n: 26, name: "Moon Knight" },
        { n: 27, name: "Lockheed" },
        { n: 28, name: "Aunt May Parker" },
        { n: 29, name: "Spider-Man" },
        { n: 30, name: "Cosmic Spider-Man" },
        { n: 31, name: "Captain America" },
        { n: 32, name: "Silver Surfer" },
        { n: 33, name: "Human Torch" },
        { n: 34, name: "Doctor Strange" },
        { n: 35, name: "Havok" },
        { n: 36, name: "Colossus" },
        { n: 37, name: "Wolverine" },
        { n: 38, name: "Nightcrawler" },
        { n: 39, name: "She-Hulk" },
        { n: 40, name: "Captain Britain" },
        { n: 41, name: "Rogue" },
        { n: 42, name: "Iron Man" },
        { n: 43, name: "Invisible Woman" },
        { n: 44, name: "Punisher's Battle Van" },
        { n: 45, name: "Longshot" },
        { n: 46, name: "Beast" },
        { n: 47, name: "Deathlok" },
        { n: 48, name: "Cloak" },
        { n: 49, name: "Punisher" },
        { n: 50, name: "Night Thrasher" },
        { n: 51, name: "Magneto" },
        { n: 52, name: "Wonder Man" },
        { n: 53, name: "Ghost Rider" },
        { n: 54, name: "Iron Man" },
        { n: 55, name: "US Agent" },
        { n: 56, name: "Wasp" },
        { n: 57, name: "Silver Sable" },
        { n: 58, name: "Ant-Man" },
        { n: 59, name: "Hawkeye" },
        { n: 60, name: "Havok" },
        { n: 61, name: "Doctor Doom" },
        { n: 62, name: "Magneto" },
        { n: 63, name: "Doctor Octopus" },
        { n: 64, name: "Kingpin" },
        { n: 65, name: "Red Skull" },
        { n: 66, name: "Sabretooth" },
        { n: 67, name: "Loki" },
        { n: 68, name: "Juggernaut" },
        { n: 69, name: "Hobgoblin" },
        { n: 70, name: "Mysterio" },
        { n: 71, name: "The Blob" },
        { n: 72, name: "Black Cat" },
        { n: 73, name: "Venom" },
        { n: 74, name: "Green Goblin" },
        { n: 75, name: "Galactus" },
        { n: 76, name: "Mandarin" },
        { n: 77, name: "High Evolutionary" },
        { n: 78, name: "Mephisto" },
        { n: 79, name: "Thanos" },
        { n: 80, name: "Apocalypse" },
        { n: 81, name: "Red Skull" },
        { n: 82, name: "Ghost Rider" },
        { n: 83, name: "Deathlok" },
        { n: 84, name: "Guardians of the Galaxy" },
        { n: 85, name: "New Warriors" },
        { n: 86, name: "Nomad" },
        { n: 87, name: "Foolkiller" },
        { n: 88, name: "Thing vs. Hulk" },
        { n: 89, name: "Fantastic Four vs. Galactus" },
        { n: 90, name: "Fantastic Four vs. Doctor Doom" },
        { n: 91, name: "Thor vs. Surtur" },
        { n: 92, name: "Spider-Man vs. Kraven" },
        { n: 93, name: "Spider-Man vs. Dr. Octopus" },
        { n: 94, name: "Daredevil vs. Bullseye" },
        { n: 95, name: "Daredevil vs. Kingpin" },
        { n: 96, name: "Silver Surfer vs. Mephisto" },
        { n: 97, name: "Captain America vs. The Red Skull" },
        { n: 98, name: "Dark Phoenix Saga" },
        { n: 99, name: "X-Men vs. The Avengers" },
        { n: 100, name: "X-Men vs. Magneto" },
        { n: 101, name: "Fantastic Four vs. X-Men" },
        { n: 102, name: "Fall of the Mutants" },
        { n: 103, name: "The Evolutionary War" },
        { n: 104, name: "Atlantis Attacks" },
        { n: 105, name: "Acts of Vengeance" },
        { n: 106, name: "Spider-Man vs. Venom" },
        { n: 107, name: "Nick Fury vs. Hydra" },
        { n: 108, name: "Armor Wars I" },
        { n: 109, name: "Daredevil vs. Wolverine" },
        { n: 110, name: "Daredevil vs. Punisher" },
        { n: 111, name: "Spider-Man vs. Green Goblin" },
        { n: 112, name: "Spider-Man vs. Hobgoblin" },
        { n: 113, name: "The Hulk vs. Wolverine" },
        { n: 114, name: "The Hulk vs. Spider-Man" },
        { n: 115, name: "Captain America vs. Wolverine" },
        { n: 116, name: "Silver Surfer vs. Thanos" },
        { n: 117, name: "X-Factor vs. Apocalypse" },
        { n: 118, name: "X-Men vs. Freedom Force" },
        { n: 119, name: "Wolverine vs. Sabretooth" },
        { n: 120, name: "X-Men in the Savage Land" },
        { n: 121, name: "Iron Man vs. Titanium Man" },
        { n: 122, name: "Thor vs. Loki" },
        { n: 123, name: "The Kree-Skrull War" },
        { n: 124, name: "Fantastic Four #1" },
        { n: 125, name: "X-Men #1" },
        { n: 126, name: "Amazing Fantasy #15" },
        { n: 127, name: "Punisher #1" },
        { n: 128, name: "Journey into Mystery #83" },
        { n: 129, name: "Amazing Spider-Man #129" },
        { n: 130, name: "Avengers #1" },
        { n: 131, name: "Amazing Spider-Man #1" },
        { n: 132, name: "Giant-Size X-Men #1" },
        { n: 133, name: "Wolverine #1" },
        { n: 134, name: "Incredible Hulk #181" },
        { n: 135, name: "Tales of Suspense #39" },
        { n: 136, name: "Avengers #4" },
        { n: 137, name: "Fantastic Four" },
        { n: 138, name: "Avengers" },
        { n: 139, name: "X-Men" },
        { n: 140, name: "X-Men (Old Team)" },
        { n: 141, name: "Cloak and Dagger" },
        { n: 142, name: "New Mutants" },
        { n: 143, name: "X-Factor" },
        { n: 144, name: "Excalibur" },
        { n: 145, name: "Brotherhood of Evil Mutants" },
        { n: 146, name: "Sinister Six" },
        { n: 147, name: "Hellfire Club" },
        { n: 148, name: "Alpha Flight" },
        { n: 149, name: "Spider-Man Presents: Spider-Man" },
        { n: 150, name: "Spider-Man Presents: Doctor Doom" },
        { n: 151, name: "Spider-Man Presents: Doctor Octopus" },
        { n: 152, name: "Spider-Man Presents: The Hulk" },
        { n: 153, name: "Spider-Man Presents: Silver Surfer" },
        { n: 154, name: "Spider-Man Presents: Thor" },
        { n: 155, name: "Spider-Man Presents: Punisher" },
        { n: 156, name: "Spider-Man Presents: Magneto" },
        { n: 157, name: "Spider-Man Presents: Wolverine" },
        { n: 158, name: "Spider-Man Presents: Captain America" },
        { n: 159, name: "Spider-Man Presents: Green Goblin" },
        { n: 160, name: "Spider-Man Presents: Ghost Rider" },
        { n: 161, name: "Stan Lee" },
        { n: 162, name: "Checklist" }
    ],
    holoCards: [
        { id: "MH1", n: 1, name: "Cosmic Spider-Man Hologram" },
        { id: "MH2", n: 2, name: "Magneto Hologram" },
        { id: "MH3", n: 3, name: "Silver Surfer Hologram" },
        { id: "MH4", n: 4, name: "Wolverine Hologram" },
        { id: "MH5", n: 5, name: "Spider-Man vs. Green Goblin Hologram" }
    ]
};