// data-mu1990.js
export const MU1990_DATA = {
    baseCards: [
        { n: 1, name: "Captain America" }, { n: 2, name: "Spider-Man" }, { n: 3, name: "Hulk" },
        { n: 4, name: "Daredevil" }, { n: 5, name: "Nick Fury" }, { n: 6, name: "Thing" },
        { n: 7, name: "Professor X" }, { n: 8, name: "Cyclops" }, { n: 9, name: "Marvel Girl" },
        { n: 10, name: "Wolverine" }, { n: 11, name: "Phoenix" }, { n: 12, name: "Power Man" },
        { n: 13, name: "Dazzler" }, { n: 14, name: "Dagger" }, { n: 15, name: "Quasar" },
        { n: 16, name: "Sub-Mariner" }, { n: 17, name: "Hulk" }, { n: 18, name: "Thor" },
        { n: 19, name: "Mister Fantastic" }, { n: 20, name: "Black Panther" }, { n: 21, name: "Iceman" },
        { n: 22, name: "Storm" }, { n: 23, name: "Human Torch" }, { n: 24, name: "Iron Man" },
        { n: 25, name: "Invisible Woman" }, { n: 26, name: "Punisher" }, { n: 27, name: "Silver Surfer" },
        { n: 28, name: "Ghost Rider" }, { n: 29, name: "Moon Knight" }, { n: 30, name: "Deathlok" },
        { n: 31, name: "Havok" }, { n: 32, name: "Archangel" }, { n: 33, name: "She-Hulk" },
        { n: 34, name: "Cloak" }, { n: 35, name: "Colossus" }, { n: 36, name: "Beast" },
        { n: 37, name: "Nightcrawler" }, { n: 38, name: "Hawkeye" }, { n: 39, name: "Namorita" },
        { n: 40, name: "Dr. Strange" }, { n: 41, name: "Black Widow" }, { n: 42, name: "Falcon" },
        { n: 43, name: "Shang-Chi" }, { n: 44, name: "Spider-Woman" }, { n: 45, name: "Quicksilver" },
        { n: 46, name: "Rogue" }, { n: 47, name: "Wasp" }, { n: 48, name: "Cable" },
        { n: 49, name: "Magneto" }, { n: 50, name: "Doctor Doom" }, { n: 51, name: "The Kingpin" },
        { n: 52, name: "Green Goblin" }, { n: 53, name: "The Joker" }, { n: 54, name: "Loki" },
        { n: 55, name: "Galactus" }, { n: 56, name: "Thanos" }, { n: 57, name: "The Mandarin" },
        { n: 58, name: "Ultron" }, { n: 59, name: "Doctor Octopus" }, { n: 60, name: "Red Skull" },
        { n: 61, name: "Apocalypse" }, { n: 62, name: "The Blob" }, { n: 63, name: "Juggernaut" },
        { n: 64, name: "Sabretooth" }, { n: 65, name: "Mystique" }, { n: 66, name: "Mister Sinister" },
        { n: 67, name: "The Lizard" }, { n: 68, name: "Venom" }, { n: 69, name: "Bullseye" },
        { n: 70, name: "Sandman" }, { n: 71, name: "Rhino" }, { n: 72, name: "Abomination" },
        { n: 73, name: "Mephisto" }, { n: 74, name: "Hobgoblin" }, { n: 75, name: "High Evolutionary" },
        { n: 76, name: "The Leader" }, { n: 77, name: "Crossbones" }, { n: 78, name: "Stane" },
        { n: 79, name: "Blackout" }, { n: 80, name: "Caliban" }, { n: 81, name: "Super-Skrull" },
        { n: 82, name: "Nightmare" }, { n: 83, name: "Enchantress" }, { n: 84, name: "Carnage" },
        { n: 85, name: "Sub-Mariner" }, { n: 86, name: "Fantastic Four" }, { n: 87, name: "Avengers" },
        { n: 88, name: "X-Men" }, { n: 89, name: "New Mutants" }, { n: 90, name: "X-Factor" },
        { n: 91, name: "Excalibur" }, { n: 92, name: "Alpha Flight" }, { n: 93, name: "West Coast Avengers" },
        { n: 94, name: "Inhumans" }, { n: 95, name: "Guardians of the Galaxy" }, { n: 96, name: "Damage Control" },
        { n: 97, name: "Sinister Six" }, { n: 98, name: "The Cabal" }, { n: 99, name: "The Marauders" },
        { n: 100, name: "The Reavers" }, { n: 101, name: "Captain America vs. Red Skull" }, { n: 102, name: "Spider-Man vs. Green Goblin" },
        { n: 103, name: "Hulk vs. Abomination" }, { n: 104, name: "Daredevil vs. Bullseye" }, { n: 105, name: "Fantastic Four vs. Galactus" },
        { n: 106, name: "Silver Surfer vs. Thanos" }, { n: 107, name: "Wolverine vs. Sabretooth" }, { n: 108, name: "Thor vs. Loki" },
        { n: 109, name: "Iron Man vs. Mandarin" }, { n: 110, name: "X-Men vs. Magneto" }, { n: 111, name: "Spider-Man vs. Venom" },
        { n: 112, name: "Avengers vs. Ultron" }, { n: 113, name: "Nick Fury vs. Baron Strucker" }, { n: 114, name: "Shield vs. Hydra" },
        { n: 115, name: "Punisher vs. Jigsaw" }, { n: 116, name: "Spider-Man vs. Doctor Octopus" }, { n: 117, name: "Hulk vs. Thing" },
        { n: 118, name: "Silver Surfer vs. Mephisto" }, { n: 119, name: "Quasar vs. Maelstrom" }, { n: 120, name: "Ghost Rider vs. Blackout" },
        { n: 121, name: "Spider-Man" }, { n: 122, name: "Captain America" }, { n: 123, name: "Iron Man" },
        { n: 124, name: "Hulk" }, { n: 125, name: "Thor" }, { n: 126, name: "Wolverine" },
        { n: 127, name: "Silver Surfer" }, { n: 128, name: "Punisher" }, { n: 129, name: "Fantastic Four" },
        { n: 130, name: "Doctor Doom" }, { n: 131, name: "Magneto" }, { n: 132, name: "Venom" },
        { n: 133, name: "Galactus" }, { n: 134, name: "Ghost Rider" }, { n: 135, name: "Deathlok" },
        { n: 136, name: "Daredevil" }, { n: 137, name: "Nick Fury" }, { n: 138, name: "Thing" },
        { n: 139, name: "Cyclops" }, { n: 140, name: "Storm" }, { n: 141, name: "Jean Grey" },
        { n: 142, name: "Colossus" }, { n: 143, name: "Beast" }, { n: 144, name: "Nightcrawler" },
        { n: 145, name: "Rogue" }, { n: 146, name: "Archangel" }, { n: 147, name: "Havok" },
        { n: 148, name: "Cable" }, { n: 149, name: "She-Hulk" }, { n: 150, name: "Hawkeye" },
        { n: 151, name: "Dr. Strange" }, { n: 152, name: "Black Widow" }, { n: 153, name: "Sub-Mariner" },
        { n: 154, name: "Moon Knight" }, { n: 155, name: "Quasar" }, { n: 156, name: "Cloak & Dagger" },
        { n: 157, name: "Green Goblin" }, { n: 158, name: "Red Skull" }, { n: 159, name: "Doctor Octopus" },
        { n: 160, name: "Juggernaut" }, { n: 161, name: "Sabretooth" }, { n: 162, name: "Kingpin" },
        { n: 163, name: "Bullseye" }, { n: 164, name: "Apocalypse" }, { n: 165, name: "Lizard" },
        { n: 166, name: "Rhino" }, { n: 167, name: "Checklist" }
    ],
    holoCards: [
        { id: 'MH1', n: 1, name: "Cosmic Spider-Man" }, { id: 'MH2', n: 2, name: "Magneto" },
        { id: 'MH3', n: 3, name: "Silver Surfer" }, { id: 'MH4', n: 4, name: "Wolverine" },
        { id: 'MH5', n: 5, name: "The Hulk" }
    ]
};