// data-mm1993.js
export const MM1993_DATA = {
    name: "Marvel Masterpieces 1993",
    maxCount: 98,
    baseCards: [
        { n: 1, name: "Hulk" },
        { n: 2, name: "Human Torch" },
        { n: 3, name: "Thor" },
        { n: 4, name: "Iron Man" },
        { n: 5, name: "Spider-Man" },
        { n: 6, name: "Wolverine" },
        { n: 7, name: "Cyclops" },
        { n: 8, name: "Doctor Strange" },
        { n: 9, name: "Namor" },
        { n: 10, name: "Storm" },
        { n: 11, name: "Silver Surfer" },
        { n: 12, name: "Vision" },
        { n: 13, name: "Ghost Rider" },
        { n: 14, name: "Thing" },
        { n: 15, name: "Captain America" },
        { n: 16, name: "Archangel" },
        { n: 17, name: "Beast" },
        { n: 18, name: "Cable" },
        { n: 19, name: "Carnage" },
        { n: 20, name: "Hulk 2099" },
        { n: 21, name: "Doctor Doom" },
        { n: 22, name: "Daredevil" },
        { n: 23, name: "Iron Fist" },
        { n: 24, name: "Psylocke" },
        { n: 25, name: "Morbius" },
        { n: 26, name: "Punisher" },
        { n: 27, name: "Rogue" },
        { n: 28, name: "Sabretooth" },
        { n: 29, name: "Forge" },
        { n: 30, name: "She-Hulk" },
        { n: 31, name: "Gambit" },
        { n: 32, name: "U.S. Agent" },
        { n: 33, name: "Spider-Woman" },
        { n: 34, name: "Stryfe" },
        { n: 35, name: "Spider-Man 2099" },
        { n: 36, name: "Domino" },
        { n: 37, name: "Thanos" },
        { n: 38, name: "Colossus" },
        { n: 39, name: "War Machine" },
        { n: 40, name: "Darkhawk" },
        { n: 41, name: "Doom 2099" },
        { n: 42, name: "Punisher 2099" },
        { n: 43, name: "Ravage 2099" },
        { n: 44, name: "Vengeance" },
        { n: 45, name: "Venom" },
        { n: 46, name: "Bishop" },
        { n: 47, name: "Galactus" },
        { n: 48, name: "Rhino" },
        { n: 49, name: "Loki" },
        { n: 50, name: "Cannonball" },
        { n: 51, name: "Polaris" },
        { n: 52, name: "Omega Red" },
        { n: 53, name: "Quasar" },
        { n: 54, name: "Cyber" },
        { n: 55, name: "Deadpool" },
        { n: 56, name: "Kingpin" },
        { n: 57, name: "Hobgoblin" },
        { n: 58, name: "Juggernaut" },
        { n: 59, name: "Jean Grey" },
        { n: 60, name: "Falcon" },
        { n: 61, name: "Wonder Man" },
        { n: 62, name: "Magneto" },
        { n: 63, name: "Doctor Octopus" },
        { n: 64, name: "Wasp" },
        { n: 65, name: "Havok" },
        { n: 66, name: "Mister Fantastic" },
        { n: 67, name: "Spider-Man" },
        { n: 68, name: "Adam Warlock" },
        { n: 69, name: "In-Betweener" },
        { n: 70, name: "Mephisto" },
        { n: 71, name: "Deathlok" },
        { n: 72, name: "Nightcrawler" },
        { n: 73, name: "Beta Ray Bill" },
        { n: 74, name: "Invisible Woman" },
        { n: 75, name: "Super-Skrull" },
        { n: 76, name: "Shatterstar" },
        { n: 77, name: "Surtur" },
        { n: 78, name: "Night Thrasher" },
        { n: 79, name: "Red Skull" },
        { n: 80, name: "Jubilee" },
        { n: 81, name: "Savage Land" },
        { n: 82, name: "Maximum Carnage" },
        { n: 83, name: "X-Cutioner's Song" },
        { n: 84, name: "Infinity Crusade" },
        { n: 85, name: "Phoenix" },
        { n: 86, name: "Mjolnir" },
        { n: 87, name: "Ultimate Invasions" },
        { n: 88, name: "Lethal Foes" },
        { n: 89, name: "Fatal Attractions" },
        { n: 90, name: "Checklist" }
    ],
    dynaCards: [
        { id: "S1", n: 1, name: "Meanstreak" },
        { id: "S2", n: 2, name: "Cerebra" },
        { id: "S3", n: 3, name: "Krystalin" },
        { id: "S4", n: 4, name: "Metalhead" },
        { id: "S5", n: 5, name: "Serpentina" },
        { id: "S6", n: 6, name: "Bloodhawk" },
        { id: "S7", n: 7, name: "Skullfire" },
        { id: "S8", n: 8, name: "Xi'an" }
    ]
};