// data-gpk1.js
export const GPK1_DATA = {
    baseCards: [
        { n: 1, v: 'a', name: 'Nasty Nick' },         { n: 1, v: 'b', name: 'Evil Eddie' },
        { n: 2, v: 'a', name: 'Junkfood John' },      { n: 2, v: 'b', name: 'Ray Decay' },
        { n: 3, v: 'a', name: 'Up Chuck' },           { n: 3, v: 'b', name: 'Heavin` Steven' },
        { n: 4, v: 'a', name: 'Fryin` Brian' },      { n: 4, v: 'b', name: 'Electric Bill' },
        { n: 5, v: 'a', name: 'Dead Ted' },           { n: 5, v: 'b', name: 'Jay Decay' },
        { n: 6, v: 'a', name: 'Art Apart' },          { n: 6, v: 'b', name: 'Busted Bob' },
        { n: 7, v: 'a', name: 'Stormy Heather' },     { n: 7, v: 'b', name: 'April Showers' },
        { n: 8, v: 'a', name: 'Adam Bomb' },          { n: 8, v: 'b', name: 'Blasted Billy' },
        { n: 9, v: 'a', name: 'Boozin` Bruce' },      { n: 9, v: 'b', name: 'Drunk Ken' },
        { n: 10, v: 'a', name: 'Tee-Vee Stevie' },    { n: 10, v: 'b', name: 'Geeky Gary' },
        { n: 11, v: 'a', name: 'Itchy Richie' },      { n: 11, v: 'b', name: 'Bugged Bert' },
        { n: 12, v: 'a', name: 'Fur Hair' },          { n: 12, v: 'b', name: 'Hairy Harriet' },
        { n: 13, v: 'a', name: 'Ashcan Andy' },       { n: 13, v: 'b', name: 'Spacey Stacy' },
        { n: 14, v: 'a', name: 'Potty Scotty' },      { n: 14, v: 'b', name: 'Jason Basin' },
        { n: 15, v: 'a', name: 'Ailin` Al' },          { n: 15, v: 'b', name: 'Mauled Mort' },
        { n: 16, v: 'a', name: 'Weird Wendy' },       { n: 16, v: 'b', name: 'Hagatha' },
        { n: 17, v: 'a', name: 'Wacky Jackie' },      { n: 17, v: 'b', name: 'Loony Lenny' },
        { n: 18, v: 'a', name: 'Cranky Kevin' },      { n: 18, v: 'b', name: 'Leaky Lou' },
        { n: 19, v: 'a', name: 'Corroded Carl' },     { n: 19, v: 'b', name: 'Crater Chris' },
        { n: 20, v: 'a', name: 'Swollen Sue' },       { n: 20, v: 'b', name: 'Blown Joan' },
        { n: 21, v: 'a', name: 'Virus lris' },        { n: 21, v: 'b', name: 'Sicky Vicky' },
        { n: 22, v: 'a', name: 'Stinky Stan' },       { n: 22, v: 'b', name: 'Spewy Lw' },
        { n: 23, v: 'a', name: 'Drippy Dan' },        { n: 23, v: 'b', name: 'Leaky Lindsay' },
        { n: 24, v: 'a', name: 'Nervous Rex' },       { n: 24, v: 'b', name: 'Tim Tremor' },
        { n: 25, v: 'a', name: 'Creepy Carol' },      { n: 25, v: 'b', name: 'Scary Carrie' },
        { n: 26, v: 'a', name: 'Gory Rory' },          { n: 26, v: 'b', name: 'Slain Wayne' },
        { n: 27, v: 'a', name: 'Brainy Janie' },      { n: 27, v: 'b', name: 'Jenny Genius' },
        { n: 28, v: 'a', name: 'Oozing Mitch' },      { n: 28, v: 'b', name: 'Sloppy Joe' },
        { n: 29, v: 'a', name: 'Bony Joanie' },       { n: 29, v: 'b', name: 'Thin Lynn' },
        { n: 30, v: 'a', name: 'New Wave Dave' },     { n: 30, v: 'b', name: 'Graffiti Petey' },
        { n: 31, v: 'a', name: 'Runaway Ron' },       { n: 31, v: 'b', name: 'Liaa' },
        { n: 32, v: 'a', name: 'Meltin` Milton' },    { n: 32, v: 'b', name: 'Third Eye Guy' },
        { n: 33, v: 'a', name: 'Mad Mike' },          { n: 33, v: 'b', name: 'Savage Stuart' },
        { n: 34, v: 'a', name: 'Kim Kong' },          { n: 34, v: 'b', name: 'Anna Banana' },
        { n: 35, v: 'a', name: 'Wrinkly Randy' },     { n: 35, v: 'b', name: 'Rockin` Robert' },
        { n: 36, v: 'a', name: 'Tommy lnmo' },        { n: 36, v: 'b', name: 'Double Heather' },
        { n: 37, v: 'a', name: 'Cindy Lopper' },      { n: 37, v: 'b', name: 'Fluorescent Florence' },
        { n: 38, v: 'a', name: 'Lizard Liz' },        { n: 38, v: 'b', name: 'King Kong' },
        { n: 39, v: 'a', name: 'Buggy Betty' },       { n: 39, v: 'b', name: 'Termite Tom' },
        { n: 40, v: 'a', name: 'Unstitched Mitch' },   { n: 40, v: 'b', name: 'Damaged Don' },
        { n: 41, v: 'a', name: 'Buster' },            { n: 41, v: 'b', name: 'Stoned Sean' }
    ]
};