// data-mm1992.js
export const MM1992_DATA = {
    name: "Marvel Masterpieces 1992",
    maxCount: 105,
    baseCards: [
        { n: 1, name: "Spider-Man" },
        { n: 2, name: "Spider-Man (Black Costume)" },
        { n: 3, name: "Spider-Man (Armor)" },
        { n: 4, name: "Hobgoblin" },
        { n: 5, name: "Green Goblin" },
        { n: 6, name: "Venom" },
        { n: 7, name: "Doctor Octopus" },
        { n: 8, name: "Lizard" },
        { n: 9, name: "Carnage" },
        { n: 10, name: "Kingpin" },
        { n: 11, name: "Daredevil" },
        { n: 12, name: "Bullseye" },
        { n: 13, name: "Elektra" },
        { n: 14, name: "Punisher" },
        { n: 15, name: "Microchip" },
        { n: 16, name: "Jigsaw" },
        { n: 17, name: "Captain America" },
        { n: 18, name: "Red Skull" },
        { n: 19, name: "US Agent" },
        { n: 20, name: "Falcon" },
        { n: 21, name: "Iron Man" },
        { n: 22, name: "Iron Man (Stealth)" },
        { n: 23, name: "War Machine" },
        { n: 24, name: "Mandarin" },
        { n: 25, name: "Thor" },
        { n: 26, name: "Loki" },
        { n: 27, name: "Hela" },
        { n: 28, name: "Beta Ray Bill" },
        { n: 29, name: "Hulk" },
        { n: 30, name: "Hulk (Gray)" },
        { n: 31, name: "She-Hulk" },
        { n: 32, name: "Abomination" },
        { n: 33, name: "Leader" },
        { n: 34, name: "Wolverine" },
        { n: 35, name: "Wolverine (Weapon X)" },
        { n: 36, name: "Sabretooth" },
        { n: 37, name: "Cyclops" },
        { n: 38, name: "Jean Grey" },
        { n: 39, name: "Archangel" },
        { n: 40, name: "Iceman" },
        { n: 41, name: "Beast" },
        { n: 42, name: "Professor X" },
        { n: 43, name: "Storm" },
        { n: 44, name: "Colossus" },
        { n: 45, name: "Nightcrawler" },
        { n: 46, name: "Rogue" },
        { n: 47, name: "Gambit" },
        { n: 48, name: "Jubilee" },
        { n: 49, name: "Psylocke" },
        { n: 50, name: "Shadowcat" },
        { n: 51, name: "Magneto" },
        { n: 52, name: "Mystique" },
        { n: 53, name: "Juggernaut" },
        { n: 54, name: "Apocalypse" },
        { n: 55, name: "Mr. Sinister" },
        { n: 56, name: "Omega Red" },
        { n: 57, name: "Mojo" },
        { n: 58, name: "Cable" },
        { n: 59, name: "Domino" },
        { n: 60, name: "Shatterstar" },
        { n: 61, name: "Deadpool" },
        { n: 62, name: "Stryfe" },
        { n: 63, name: "Silver Surfer" },
        { n: 64, name: "Galactus" },
        { n: 65, name: "Thanos" },
        { n: 66, name: "Adam Warlock" },
        { n: 67, name: "Quasar" },
        { n: 68, name: "Doctor Doom" },
        { n: 69, name: "Mister Fantastic" },
        { n: 70, name: "Invisible Woman" },
        { n: 71, name: "Human Torch" },
        { n: 72, name: "Thing" },
        { n: 73, name: "Namor" },
        { n: 74, name: "Namorita" },
        { n: 75, name: "Nick Fury" },
        { n: 76, name: "Black Widow" },
        { n: 77, name: "Hawkeye" },
        { n: 78, name: "Vision" },
        { n: 79, name: "Scarlet Witch" },
        { n: 80, name: "Wonder Man" },
        { n: 81, name: "Black Panther" },
        { n: 82, name: "Doctor Strange" },
        { n: 83, name: "Ghost Rider" },
        { n: 84, name: "Johnny Blaze" },
        { n: 85, name: "Morbius" },
        { n: 86, name: "Sleepwalker" },
        { n: 87, name: "Deathlok" },
        { n: 88, name: "Night Thrasher" },
        { n: 89, name: "Darkhawk" },
        { n: 90, name: "Nova" },
        { n: 91, name: "Spider-Man vs. Venom" },
        { n: 92, name: "Captain America vs. Red Skull" },
        { n: 93, name: "Wolverine vs. Sabretooth" },
        { n: 94, name: "Hulk vs. Thing" },
        { n: 95, name: "Silver Surfer vs. Thanos" },
        { n: 96, name: "Daredevil vs. Bullseye" },
        { n: 97, name: "Iron Man vs. Mandarin" },
        { n: 98, name: "Thor vs. Loki" },
        { n: 99, name: "Fantastic Four vs. Doctor Doom" },
        { n: 100, name: "X-Men vs. Magneto" }
    ],
    spectraCards: [
        { id: "BS1", n: 1, name: "Spider-Man vs. Venom" },
        { id: "BS2", n: 2, name: "Captain America vs. Red Skull" },
        { id: "BS3", n: 3, name: "Wolverine vs. Sabretooth" },
        { id: "BS4", n: 4, name: "Hulk vs. Thing" },
        { id: "BS5", n: 5, name: "Silver Surfer vs. Thanos" }
    ]
};