// sets-config.js - Central Set Registry for Rip Boosters

export const SETS_REGISTRY = [
    // --- MAGIC: THE GATHERING ---
    {
        key: 'mtglea',
        name: 'Limited Edition Alpha',
        year: 1993,
        publisher: 'WotC',
        category: 'Magic: The Gathering',
        totalCards: 295,
        coverImage: 'card_images/mtg_sets/mtg_alpha_beta_pack_wrapper.jpg',
        themeColor: '#e5b35c',
        isMtg: true,
        seoTitle: 'MTG Limited Edition Alpha Booster Simulator - Rip Boosters',
        seoDesc: 'Simulate opening historic 1993 MTG Alpha booster packs. Chase the Power Nine, Black Lotus, and original white-bordered rares.',
        aboutTitle: 'Magic: The Gathering – Limited Edition Alpha (1993)',
        aboutText: "Released in August 1993, Limited Edition Alpha (LEA) is the historic set that started it all. With a black-bordered print run of just 295 cards, it introduced players to Richard Garfield's revolutionary trading card game. Collectors and enthusiasts rip into these packs chasing the legendary 'Power Nine'—including the mythical Black Lotus—and early, powerful artifacts, alongside lands and original creature printings."
    },
    {
        key: 'mtgleb',
        name: 'Limited Edition Beta',
        year: 1993,
        publisher: 'WotC',
        category: 'Magic: The Gathering',
        totalCards: 302,
        coverImage: 'card_images/mtg_sets/mtg_alpha_beta_pack_wrapper.jpg',
        themeColor: '#a5c0d6',
        isMtg: true,
        seoTitle: 'MTG Limited Edition Beta Booster Simulator - Rip Boosters',
        seoDesc: 'Rip 1993 MTG Beta packs. Trace rare Dual Lands and historical original cards using accurate pull probabilities.',
        aboutTitle: 'Magic: The Gathering – Limited Edition Beta (1993)',
        aboutText: 'Released in October 1993, Limited Edition Beta (LEB) followed immediately after Alpha to correct print errors, slightly adjusting card corners and adding missing cards like Volcanic Island and Cop: Black. This black-bordered 302-card set represents the most polished form of the original release.'
    },
    {
        key: 'mtg2ed',
        name: 'Unlimited Edition',
        year: 1993,
        publisher: 'WotC',
        category: 'Magic: The Gathering',
        totalCards: 302,
        coverImage: 'card_images/mtg_sets/mtg_unlimited_pack_wrapper.jpg',
        themeColor: '#8bc47e',
        isMtg: true,
        seoTitle: 'MTG Unlimited Edition Booster Simulator - Rip Boosters',
        seoDesc: 'Open Unlimited Edition white-bordered MTG booster packs from 1993.',
        aboutTitle: 'Magic: The Gathering – Unlimited Edition (1993)',
        aboutText: 'Released in December 1993, Unlimited Edition (2ED) was the first white-bordered reprint set of Magic: The Gathering. To meet massive consumer demand, Wizards of the Coast printed this 302-card set as a direct replica of Beta.'
    },
    {
        key: 'mtgarn',
        name: 'Arabian Nights',
        year: 1993,
        publisher: 'WotC',
        category: 'Magic: The Gathering',
        totalCards: 92,
        coverImage: 'card_images/mtg_sets/mtg_arn_pack_wrapper.jpg',
        themeColor: '#dfbc6c',
        isMtg: true,
        seoTitle: 'MTG Arabian Nights Pack Simulator - Rip Boosters',
        seoDesc: "Explore Magic's very first expansion. Open Arabian Nights booster wrappers and search for Bazaar of Baghdad.",
        aboutTitle: 'Magic: The Gathering – Arabian Nights (1993)',
        aboutText: 'Released in December 1993, Arabian Nights is the very first expansion set for Magic: The Gathering. Drawing inspiration from One Thousand and One Nights, it introduced iconic cards like Juzám Djinn and Bazaar of Baghdad.'
    },
    {
        key: 'mtgatq',
        name: 'Antiquities',
        year: 1994,
        publisher: 'WotC',
        category: 'Magic: The Gathering',
        totalCards: 100,
        coverImage: 'card_images/mtg_sets/mtg_atq_pack_wrapper.jpg',
        themeColor: '#bca07c',
        isMtg: true,
        seoTitle: 'MTG Antiquities Booster Simulator - Rip Boosters',
        seoDesc: 'Open artifact-rich 1994 MTG Antiquities packs online and follow the brothers Urza and Mishra.',
        aboutTitle: 'Magic: The Gathering – Antiquities (1994)',
        aboutText: "Released in March 1994, Antiquities tells the tragic story of the brothers Urza and Mishra and their devastating war. This artifact-focused set introduced legendary mechanics and the 'UrzaTron' land cycle."
    },
    {
        key: 'mtg3ed',
        name: 'Revised Edition',
        year: 1994,
        publisher: 'WotC',
        category: 'Magic: The Gathering',
        totalCards: 306,
        coverImage: 'card_images/mtg_sets/mtg_3ed_revised_pack_wrapper.jpg',
        themeColor: '#e5b35c',
        isMtg: true,
        seoTitle: 'MTG Revised Edition Booster Simulator - Rip Boosters',
        seoDesc: 'Rip classic 1994 Revised Edition booster packs. Collect iconic Dual Lands and early core base cards.',
        aboutTitle: 'Magic: The Gathering – Revised Edition (1994)',
        aboutText: 'Released in April 1994, Revised Edition (3ED) marked a massive growing point for Magic: The Gathering. This 306-card white-bordered core set became the definitive MTG experience for many early players.'
    },
    {
        key: 'mtgleg',
        name: 'Legends',
        year: 1994,
        publisher: 'WotC',
        category: 'Magic: The Gathering',
        totalCards: 310,
        coverImage: 'card_images/mtg_sets/mtg_leg_pack_wrapper.jpg',
        themeColor: '#d8b155',
        isMtg: true,
        seoTitle: 'MTG Legends Booster Pack Simulator - Rip Boosters',
        seoDesc: 'Cast legendary multicolor gold cards by ripping open 1994 MTG Legends expansion packs.',
        aboutTitle: 'Magic: The Gathering – Legends (1994)',
        aboutText: 'Released in June 1994, Legends introduced the concept of legendary creatures, multicolor gold cards, and world enchantments, forever shaping the multiplayer identity of Magic.'
    },
    {
        key: 'mtgdrk',
        name: 'The Dark',
        year: 1994,
        publisher: 'WotC',
        category: 'Magic: The Gathering',
        totalCards: 119,
        coverImage: 'card_images/mtg_sets/mtg_drk_pack_wrapper.jpg',
        themeColor: '#9b1c1c',
        isMtg: true,
        seoTitle: 'MTG The Dark Pack Simulator - Rip Boosters',
        seoDesc: 'Open gothic-horror themed 1994 MTG The Dark booster packs online.',
        aboutTitle: 'Magic: The Gathering – The Dark (1994)',
        aboutText: 'Released in August 1994, The Dark explores a bleak, superstitious fantasy setting falling into ruin. Known for its gothic horror themes and eerie art.'
    },
    {
        key: 'rav',
        name: 'Ravnica: City of Guilds',
        year: 2005,
        publisher: 'WotC',
        category: 'Magic: The Gathering',
        totalCards: 306,
        coverImage: 'card_images/mtg_sets/mtg_rav_packwrapper4.jpg',
        themeColor: '#58b972',
        isMtg: true,
        seoTitle: 'MTG Ravnica Booster Simulator - Rip Boosters',
        seoDesc: 'Open 2005 Ravnica: City of Guilds booster packs. Chase original Shock Lands, Dark Confidant, and guild staples.',
        aboutTitle: 'Magic: The Gathering – Ravnica: City of Guilds (2005)',
        aboutText: "Released in October 2005, Ravnica introduced players to a world-spanning metropolis ruled by ten distinct two-color guilds. It debuted the iconic cycle of 'Shock Lands'."
    },
    {
        key: 'isd',
        name: 'Innistrad',
        year: 2011,
        publisher: 'WotC',
        category: 'Magic: The Gathering',
        totalCards: 264,
        coverImage: 'card_images/mtg_sets/mtg_isd_packwrapper1.jpg',
        themeColor: '#8199b5',
        isMtg: true,
        seoTitle: 'MTG Innistrad Booster Simulator - Rip Boosters',
        seoDesc: 'Simulate opening iconic 2011 MTG Innistrad booster packs. Hunt for Liliana of the Veil and Snapcaster Mage.',
        aboutTitle: 'Magic: The Gathering – Innistrad (2011)',
        aboutText: 'Released in September 2011, Innistrad is widely celebrated as one of the greatest Magic expansion sets ever created. Inspired by gothic horror, it introduced double-faced cards, Werewolves, and Vampires.'
    },
    {
        key: 'mtgmsh',
        name: 'Marvel Super Heroes',
        year: 2026,
        publisher: 'WotC',
        category: 'Magic: The Gathering',
        totalCards: 357,
        coverImage: 'card_images/mtg_sets/mtg_msh_collectorboosterwrapper.jpg',
        themeColor: '#e63946',
        isMtg: true,
        seoTitle: 'MTG Marvel Super Heroes Booster Simulator - Rip Boosters',
        seoDesc: 'Simulate opening 2026 MTG Marvel Super Heroes booster packs. Hunt for showcase comic panel art, iconic Avenger rares, and mythic heroes.',
        aboutTitle: 'Magic: The Gathering – Marvel Super Heroes (2026)',
        aboutText: 'Released in June 2026 as part of Universes Beyond, Marvel Super Heroes brings iconic comic book legends including Spider-Man, Wolverine, Captain America, and Iron Man into MTG with showcase comic-panel treatments and borderless scene art.'
    },
    // --- MARVEL ---
    {
        key: 'mu1990',
        name: 'Marvel Universe',
        year: 1990,
        publisher: 'Impel',
        category: 'Marvel',
        totalCards: 167,
        coverImage: 'card_images/marvel_impel_1990/marvel_impel_1990_packimage2_spiderman.jpg',
        themeColor: '#e63946',
        dataFile: './data-mu1990.js',
        dataExport: 'MU1990_DATA',
        seoTitle: '1990 Marvel Universe Series 1 Pack Simulator - Rip Boosters',
        seoDesc: 'Rip retro 1990 Marvel Universe booster wrappers online. Relive classic Impel cards and pull ultra-rare holograms.',
        aboutTitle: 'Marvel Universe (1990)',
        aboutText: 'Produced by Impel in 1990, Series I launched the modern Marvel trading card boom. Featuring iconic classic comic art, trivia-filled card backs, and power ratings.'
    },
    {
        key: 'mm1992',
        name: 'Marvel Masterpieces',
        year: 1992,
        publisher: 'SkyBox',
        category: 'Marvel',
        totalCards: 105,
        coverImage: 'card_images/marvel_masterpieces_1992/mm1992_packimage1_wolverine.jpg',
        themeColor: '#f4a261',
        dataFile: './data-mm1992.js',
        dataExport: 'MM1992_DATA',
        seoTitle: '1992 Marvel Masterpieces Pack Simulator - Rip Boosters',
        seoDesc: 'Open digital 1992 Marvel Masterpieces booster packs. Collect all 100 cards painted by Joe Jusko and chase Battle Spectra-Etch inserts.',
        aboutTitle: 'Marvel Masterpieces (1992)',
        aboutText: 'Released by SkyBox in 1992, Marvel Masterpieces forever changed the non-sports trading card industry. Every single one of the 100 base cards features fully painted artwork by legendary illustrator Joe Jusko.'
    },
    {
        key: 'xmen1992',
        name: 'The Uncanny X-Men',
        year: 1992,
        publisher: 'Impel',
        category: 'Marvel',
        totalCards: 105,
        coverImage: 'card_images/xmen_impel_1992/uncanny_xmen_1992_packimage2_teal.jpg',
        themeColor: '#00b4d8',
        dataFile: './data-xmen1992.js',
        dataExport: 'XMEN1992_DATA',
        seoTitle: '1992 Uncanny X-Men Trading Card Simulator - Rip Boosters',
        seoDesc: 'Open 1992 X-Men packs drawn entirely by Jim Lee. Assemble the full base list and catch Gold Hologram chase cards.',
        aboutTitle: 'The Uncanny X-Men (1992)',
        aboutText: "Drawn entirely by legendary comic artist Jim Lee, Impel’s 1992 X-Men set defined the visual style of Marvel's mutants for an entire generation."
    },
    {
        key: 'mm1993',
        name: 'Marvel Masterpieces',
        year: 1993,
        publisher: 'SkyBox',
        category: 'Marvel',
        totalCards: 98,
        coverImage: 'card_images/marvel_masterpieces_1993/mm1993_packimage1_silversurfer.jpg',
        themeColor: '#f4a261',
        dataFile: './data-mm1993.js',
        dataExport: 'MM1993_DATA',
        seoTitle: '1993 Marvel Masterpieces Pack Simulator - Rip Boosters',
        seoDesc: 'Open 1993 Marvel Masterpieces packs. Hunt for rare X-Men 2099 Dyna-Etch cards and gather full artwork prints.',
        aboutTitle: 'Marvel Masterpieces (1993)',
        aboutText: 'SkyBox returned in 1993 with a new approach: inviting a diverse roster of legendary fantasy and comic artists—including Jim Steranko, Boris Vallejo, and Julie Bell—to paint the Marvel universe.'
    },

    // --- POP CULTURE & CARTOONS ---
    {
        key: 'motu1984',
        name: 'Masters of the Universe',
        year: 1984,
        publisher: 'Topps',
        category: 'Pop Culture & Cartoons',
        totalCards: 110,
        coverImage: 'card_images/motu_1984/motu1984_packwrapper1.jpg',
        themeColor: '#e76f51',
        dataFile: './data-motu1984.js',
        dataExport: 'MOTU1984_DATA',
        seoTitle: '1984 Masters of the Universe Pack Simulator - Rip Boosters',
        seoDesc: 'Open 1984 Topps Masters of the Universe booster packs online. Collect all 88 cartoon cards and 22 sticker inserts.',
        aboutTitle: 'Masters of the Universe (1984)',
        aboutText: "Released by Topps in 1984 during the peak of Filmation's animated series, Masters of the Universe captured Prince Adam, Skeletor, and Castle Grayskull in trading card form."
    },
    {
        key: 'gpk1',
        name: 'Garbage Pail Kids OS1',
        year: 1985,
        publisher: 'Topps',
        category: 'Pop Culture & Cartoons',
        totalCards: 82,
        coverImage: 'card_images/gpk_series1/gpk_series1_pack_wrapper.jpg',
        themeColor: '#ffb703',
        dataFile: './data-gpk1.js',
        dataExport: 'GPK1_DATA',
        seoTitle: '1985 Garbage Pail Kids Series 1 Simulator - Rip Boosters',
        seoDesc: 'Unbox original 1985 Series 1 Garbage Pail Kids stickers. Revisit classic gross parody card sets completely free.',
        aboutTitle: 'Garbage Pail Kids: OS1 (1985)',
        aboutText: 'Released by Topps in 1985 as a gross-out parody of the Cabbage Patch Kids craze, Garbage Pail Kids became an instant pop-culture phenomenon featuring 41 uniquely disgusting characters.'
    }
];

export const STATIC_ROUTES = {
    'privacy': { mainTitle: 'Privacy Policy', subTitle: 'Legal & Compliance Disclosures', seoTitle: 'Privacy Policy - Rip Boosters', seoDesc: 'Privacy policy and data tracking rules for the Rip Boosters non-commercial simulation application.' },
    'terms': { mainTitle: 'Terms & Cookies', subTitle: 'Terms of Service & Cookie Use Agreement', seoTitle: 'Terms of Service & Cookie Policy - Rip Boosters', seoDesc: 'User agreement, acceptable use rules, and cookie tracking details for Rip Boosters.' },
    'contact': { mainTitle: 'Contact Us', subTitle: 'Help, Feedback & Support Channels', seoTitle: 'Contact Us & Technical Support - Rip Boosters', seoDesc: 'Get in touch to submit bug updates, request cards, or offer creator feedback for Rip Boosters.' }
};