export const SETS_REGISTRY = [
    // ---------------------------------------------------------------------------
    // MAGIC: THE GATHERING (Ordered Descending by Release Date)
    // ---------------------------------------------------------------------------
    {
        key: 'mtghob',
        name: 'The Hobbit',
        year: 'August 2026',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 425,
        coverImage: 'card_images/mtg_sets/mtg_hob_collectorboosterwrapper.jpg',
        themeColor: '#b08d24',
        isMtg: true,
        aboutTitle: 'About The Hobbit Collector Boosters',
        aboutText: 'Step into Middle-earth with The Hobbit Collector Booster simulation. Features serialized Gold Smaug cards, Dwarvish language foils, Scene cards, and Dragon Hoard chase hits.',
        seoTitle: 'MTG The Hobbit Collector Booster Pack Opening Simulator - Rip Boosters',
        seoDesc: 'Simulate opening MTG The Hobbit Collector Booster packs online. Chase Serialized Smaug, Dwarvish foils, and Dragon Hoard showcase cards.'
    },
    {
        key: 'mtgmsh',
        name: 'Marvel Super Heroes',
        year: 'June 2026',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 512,
        coverImage: 'card_images/mtg_sets/mtg_msh_collectorboosterwrapper.jpg',
        themeColor: '#a81c1c',
        isMtg: true,
        aboutTitle: 'About Marvel Super Heroes Collector Boosters',
        aboutText: 'Earth’s Mightiest Heroes join Magic: The Gathering. Features Avenger Mythics, Comic Panel Showcase frames, and rare Source Material cards.',
        seoTitle: 'MTG Marvel Super Heroes Collector Booster Simulator - Rip Boosters',
        seoDesc: 'Simulate opening MTG Marvel Super Heroes Collector Booster packs online with realistic drop rates and Comic Panel showcase cards.'
    },
    {
        key: 'mtgsos',
        name: 'Secrets of Strixhaven',
        year: 'April 2026',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 462,
        coverImage: 'card_images/mtg_sets/mtg_sos_collectorboosterwrapper.jpg',
        themeColor: '#3a2e70',
        isMtg: true,
        aboutTitle: 'About Secrets of Strixhaven Collector Boosters',
        aboutText: 'Return to the magical university of Strixhaven. Features Japanese Mystical Archive cards, Serialized Emeritus chase hits, and Spellcraft basic lands.',
        seoTitle: 'MTG Secrets of Strixhaven Collector Booster Simulator - Rip Boosters',
        seoDesc: 'Simulate opening MTG Secrets of Strixhaven Collector Booster packs online. Chase Japanese Mystical Archive cards and Serialized Emeritus.'
    },
    {
        key: 'mtgtmt',
        name: 'Teenage Mutant Ninja Turtles',
        year: 'March 2026',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 440,
        coverImage: 'card_images/mtg_sets/mtg_tmt_collectorboosterwrapper.jpg',
        themeColor: '#1d703e',
        isMtg: true,
        aboutTitle: 'About TMNT Collector Boosters',
        aboutText: 'Cowabunga! Rip into Teenage Mutant Ninja Turtles Collector Boosters featuring Kevin Eastman Signatures, Pizza Basic Lands, and Sewer Frame showcase cards.',
        seoTitle: 'MTG TMNT Collector Booster Pack Opener Simulator - Rip Boosters',
        seoDesc: 'Open free MTG TMNT Collector Booster simulation packs online. Hunt for Kevin Eastman Signatures and Sewer Frame showcase hits.'
    },
    {
        key: 'mtgecl',
        name: 'Lorwyn Eclipsed',
        year: 'January 2026',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 498,
        coverImage: 'card_images/mtg_sets/mtg_ecl_collectorboosterwrapper.jpg',
        themeColor: '#2d6a4f',
        isMtg: true,
        aboutTitle: 'About Lorwyn Eclipsed Collector Boosters',
        aboutText: 'Revisit the realm of Lorwyn with the Lorwyn Eclipsed Collector Booster simulator. Hunt for Serialized Bitterbloom Bearer, Japan Showcase Fracture Foils, Reversible Shock Lands, and Fable Frame Mythics.',
        seoTitle: 'MTG Lorwyn Eclipsed Collector Booster Simulator - Rip Boosters',
        seoDesc: 'Simulate opening MTG Lorwyn Eclipsed Collector Booster packs. Chase Japan Showcase Fracture Foils, Serialized Bitterbloom Bearer, and Reversible Shock Lands.'
    },
    {
        key: 'isd',
        name: 'Innistrad',
        year: '2011',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 264,
        coverImage: 'card_images/mtg_sets/mtg_isd_packwrapper1.jpg',
        themeColor: '#4a3b52',
        isMtg: true,
        aboutTitle: 'About Innistrad Booster Packs',
        aboutText: 'Step into the gothic horror world of Innistrad. Features iconic double-faced cards, Liliana of the Veil, Snapcaster Mage, and classic horror tropes.',
        seoTitle: 'MTG Innistrad Pack Opening Simulator - Rip Boosters',
        seoDesc: 'Open free MTG Innistrad booster packs online. Experience the iconic 2011 gothic horror set and pull Snapcaster Mage or Liliana of the Veil.'
    },
    {
        key: 'rav',
        name: 'Ravnica: City of Guilds',
        year: '2005',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 306,
        coverImage: 'card_images/mtg_sets/mtg_rav_packwrapper1.jpg',
        themeColor: '#8c6d3b',
        isMtg: true,
        aboutTitle: 'About Ravnica: City of Guilds',
        aboutText: 'Explore the ecumenopolis of Ravnica and its ten distinct color-pair guilds. Introduced the original cycle of Shock Lands and iconic multi-color staples.',
        seoTitle: 'MTG Ravnica City of Guilds Booster Simulator - Rip Boosters',
        seoDesc: 'Simulate opening original 2005 Ravnica: City of Guilds booster packs. Chase original Shock Lands and guild legendaries.'
    },
    {
        key: 'mtgdrk',
        name: 'The Dark',
        year: '1994',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 119,
        coverImage: 'card_images/mtg_sets/mtg_drk_pack_wrapper.jpg',
        themeColor: '#363435',
        isMtg: true,
        aboutTitle: 'About The Dark Expansion',
        aboutText: 'Released in August 1994, The Dark explored a bleak fantasy world following the aftermath of the Antiquities war. Known for Blood Moon, Maze of Ith, and gritty early artwork.',
        seoTitle: 'MTG The Dark 1994 Booster Pack Simulator - Rip Boosters',
        seoDesc: 'Simulate opening 1994 MTG The Dark booster packs online. Hunt for Maze of Ith and Blood Moon in this nostalgic retro set.'
    },
    {
        key: 'mtgleg',
        name: 'Legends',
        year: '1994',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 310,
        coverImage: 'card_images/mtg_sets/mtg_leg_pack_wrapper.jpg',
        themeColor: '#a63b28',
        isMtg: true,
        aboutTitle: 'About Legends Expansion',
        aboutText: 'Released in June 1994, Legends introduced multi-colored gold cards, legendary creatures, and world enchantments to Magic: The Gathering.',
        seoTitle: 'MTG Legends 1994 Booster Pack Opening Simulator - Rip Boosters',
        seoDesc: 'Simulate opening vintage 1994 MTG Legends booster packs online. Chase legendary dragons, The Tabernacle at Pendrell Vale, and Mana Drain.'
    },
    {
        key: 'mtgatq',
        name: 'Antiquities',
        year: '1994',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 100,
        coverImage: 'card_images/mtg_sets/mtg_atq_pack_wrapper.jpg',
        themeColor: '#966c30',
        isMtg: true,
        aboutTitle: 'About Antiquities Expansion',
        aboutText: 'Released in March 1994, Antiquities was Magic’s first lore-driven expansion, detailing the epic war between brothers Urza and Mishra.',
        seoTitle: 'MTG Antiquities 1994 Booster Pack Simulator - Rip Boosters',
        seoDesc: 'Open free vintage MTG Antiquities booster packs. Hunt for Mishra’s Workshop, Urza lands, and classic 1994 artifact cards.'
    },
    {
        key: 'mtgarn',
        name: 'Arabian Nights',
        year: '1993',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 92,
        coverImage: 'card_images/mtg_sets/mtg_arn_pack_wrapper.jpg',
        themeColor: '#2b5876',
        isMtg: true,
        aboutTitle: 'About Arabian Nights Expansion',
        aboutText: 'Released in December 1993, Arabian Nights was Magic’s very first expansion set. Inspired by 1001 Arabian Nights tales, featuring Bazaar of Baghdad and Shahrazad.',
        seoTitle: 'MTG Arabian Nights 1993 Booster Pack Simulator - Rip Boosters',
        seoDesc: 'Simulate opening 1993 MTG Arabian Nights booster packs online. Chase Bazaar of Baghdad, Library of Alexandria, and Juzám Djinn.'
    },
    {
        key: 'mtg3ed',
        name: 'Revised Edition (3rd Edition)',
        year: '1994',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 306,
        coverImage: 'card_images/mtg_sets/mtg_3ed_revised_pack_wrapper.jpg',
        themeColor: '#7a8b9e',
        isMtg: true,
        aboutTitle: 'About Revised Edition',
        aboutText: 'Released in April 1994, Revised Edition was the last core set to include Dual Lands. Features simplified rules text, white borders, and classic 1994 iconic staples.',
        seoTitle: 'MTG Revised Edition 1994 Booster Simulator - Rip Boosters',
        seoDesc: 'Open free 1994 MTG Revised Edition booster packs online. Pull Dual Lands like Underground Sea and Volcanic Island.'
    },
    {
        key: 'mtg2ed',
        name: 'Unlimited Edition',
        year: '1993',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 302,
        coverImage: 'card_images/mtg_sets/mtg_unlimited_pack_wrapper.jpg',
        themeColor: '#c9a227',
        isMtg: true,
        aboutTitle: 'About Unlimited Edition',
        aboutText: 'Released in December 1993, Unlimited Edition introduced white borders while preserving the complete original 302-card power pool from Beta.',
        seoTitle: 'MTG Unlimited Edition 1993 Booster Simulator - Rip Boosters',
        seoDesc: 'Simulate opening vintage 1993 MTG Unlimited Edition booster packs online. Pull white-bordered Power Nine and Dual Lands.'
    },
    {
        key: 'mtgleb',
        name: 'Limited Edition Beta',
        year: '1993',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 302,
        coverImage: 'card_images/mtg_sets/mtg_alpha_beta_pack_wrapper.jpg',
        themeColor: '#1a1a1a',
        isMtg: true,
        aboutTitle: 'About Limited Edition Beta',
        aboutText: 'Released in October 1993, Beta fixed misprints from Alpha and added Volcanic Island and Circle of Protection: Black to complete the original 302-card set.',
        seoTitle: 'MTG Limited Edition Beta 1993 Booster Simulator - Rip Boosters',
        seoDesc: 'Open vintage 1993 MTG Beta booster packs online. Chase Black Lotus, Dual Lands, and iconic black-bordered classics.'
    },
    {
        key: 'mtglea',
        name: 'Limited Edition Alpha',
        year: '1993',
        publisher: 'Wizards of the Coast',
        category: 'Magic: The Gathering',
        totalCards: 295,
        coverImage: 'card_images/mtg_sets/mtg_alpha_beta_pack_wrapper.jpg',
        themeColor: '#1a1a1a',
        isMtg: true,
        aboutTitle: 'About Limited Edition Alpha',
        aboutText: 'The set that started it all in August 1993. Features the original Power Nine, Dual Lands, and iconic Richard Garfield game design with distinct rounded corners.',
        seoTitle: 'MTG Limited Edition Alpha 1993 Booster Simulator - Rip Boosters',
        seoDesc: 'Simulate opening legendary 1993 MTG Alpha booster packs online. Pull Black Lotus, Moxes, and original Dual Lands.'
    },

    // ---------------------------------------------------------------------------
    // MARVEL TRADING CARDS
    // ---------------------------------------------------------------------------
    {
        key: 'mm1992',
        name: 'Marvel Masterpieces 1992',
        year: '1992',
        publisher: 'SkyBox / Impel',
        category: 'Marvel Trading Cards',
        totalCards: 105,
        coverImage: 'card_images/marvel_masterpieces_1992/mm1992_packimage1_wolverine.jpg',
        themeColor: '#df9845',
        isMtg: false,
        dataFile: './data-mm1992.js',
        dataExport: 'MM1992_DATA',
        aboutTitle: 'About Marvel Masterpieces 1992',
        aboutText: 'Painted by Joe Jusko, Marvel Masterpieces 1992 redefined non-sports trading cards. The 100-card base set features oil-painted superhero portraits, complemented by 5 rare Battle Spectra foil inserts.',
        seoTitle: 'Marvel Masterpieces 1992 Booster Pack Simulator - Rip Boosters',
        seoDesc: 'Simulate opening 1992 Marvel Masterpieces trading card packs online. Chase Joe Jusko oil-painted cards and Battle Spectra foil inserts.'
    },
    {
        key: 'mm1993',
        name: 'Marvel Masterpieces 1993',
        year: '1993',
        publisher: 'SkyBox',
        category: 'Marvel Trading Cards',
        totalCards: 98,
        coverImage: 'card_images/marvel_masterpieces_1993/mm1993_packimage1_silversurfer.jpg',
        themeColor: '#1a6a1a',
        isMtg: false,
        dataFile: './data-mm1993.js',
        dataExport: 'MM1993_DATA',
        aboutTitle: 'About Marvel Masterpieces 1993',
        aboutText: 'Featuring artwork by traditional fantasy artists, Marvel Masterpieces 1993 includes a 90-card base set and 8 iconic Dyna-Etch foil-etched insert cards.',
        seoTitle: 'Marvel Masterpieces 1993 Pack Opening Simulator - Rip Boosters',
        seoDesc: 'Open free 1993 Marvel Masterpieces trading card packs online. Collect the 90-card base set and hunt for Dyna-Etch insert cards.'
    },
    {
        key: 'mu1990',
        name: 'Marvel Universe 1990',
        year: '1990',
        publisher: 'Impel',
        category: 'Marvel Trading Cards',
        totalCards: 167,
        coverImage: 'card_images/marvel_impel_1990/marvel_impel_1990_packimage1_capam.jpg',
        themeColor: '#1a3a8a',
        isMtg: false,
        dataFile: './data-mu1990.js',
        dataExport: 'MU1990_DATA',
        aboutTitle: 'About Marvel Universe 1990 (Series 1)',
        aboutText: 'The first official Marvel Universe trading card set by Impel. Features detailed character power ratings, famous battles, and 5 rare Hologram insert cards.',
        seoTitle: 'Marvel Universe 1990 Impel Pack Simulator - Rip Boosters',
        seoDesc: 'Simulate opening 1990 Impel Marvel Universe Series 1 card packs. Chase rare Hologram inserts and classic comic character stats.'
    },
    {
        key: 'xmen1992',
        name: 'The Uncanny X-Men 1992',
        year: '1992',
        publisher: 'Impel',
        category: 'Marvel Trading Cards',
        totalCards: 105,
        coverImage: 'card_images/xmen_impel_1992/uncanny_xmen_1992_packimage1_darkblue.jpg',
        themeColor: '#b8860b',
        isMtg: false,
        dataFile: './data-xmen1992.js',
        dataExport: 'XMEN1992_DATA',
        aboutTitle: 'About The Uncanny X-Men 1992',
        aboutText: 'Illustrated by Jim Lee, this iconic set features 100 base cards, a 9-card Danger Room puzzle mural, and 5 Gold Hologram insert cards.',
        seoTitle: 'Uncanny X-Men 1992 Impel Pack Opening Simulator - Rip Boosters',
        seoDesc: 'Open 1992 Impel Uncanny X-Men booster packs online. Collect Jim Lee artwork, assemble the 3x3 puzzle mural, and pull Gold Holograms.'
    },

    // ---------------------------------------------------------------------------
    // RETRO 80S
    // ---------------------------------------------------------------------------
    {
        key: 'motu1984',
        name: 'Masters of the Universe 1984',
        year: '1984',
        publisher: 'Topps',
        category: 'Retro 80s',
        totalCards: 110,
        coverImage: 'card_images/motu_1984/motu1984_packwrapper1.jpg',
        themeColor: '#d87b28',
        isMtg: false,
        dataFile: './data-motu1984.js',
        dataExport: 'MOTU1984_DATA',
        aboutTitle: 'About Masters of the Universe 1984',
        aboutText: 'The classic 1984 Topps trading card set for He-Man and Masters of the Universe. Features 88 base cards, 22 sticker inserts, and 2x5 interlocking sticker back puzzle art.',
        seoTitle: 'Masters of the Universe 1984 Topps Pack Simulator - Rip Boosters',
        seoDesc: 'Simulate opening retro 1984 Topps Masters of the Universe He-Man card packs. Collect stickers, assemble puzzle backs, and complete the set.'
    },
    {
        key: 'gpk1',
        name: 'Garbage Pail Kids Series 1',
        year: '1985',
        publisher: 'Topps',
        category: 'Retro 80s',
        totalCards: 82,
        coverImage: 'card_images/gpk_series1/gpk_series1_pack_wrapper.jpg',
        themeColor: '#8b0000',
        isMtg: false,
        dataFile: './data-gpk1.js',
        dataExport: 'GPK1_DATA',
        aboutTitle: 'About Garbage Pail Kids Series 1 (1985)',
        aboutText: 'Created by Topps in 1985 as a parody of Cabbage Patch Kids, Series 1 features 82 die-cut sticker cards (41 "a" and "b" twin name variations) with artwork by John Pound.',
        seoTitle: 'Garbage Pail Kids Series 1 Pack Opening Simulator - Rip Boosters',
        seoDesc: 'Open free 1985 Garbage Pail Kids Series 1 sticker packs online. Collect all 82 original die-cut sticker cards and twin variations.'
    }
];

export const STATIC_ROUTES = {
    privacy: {
        seoTitle: 'Privacy Policy - Rip Boosters',
        seoDesc: 'Privacy Policy and data usage practices for Rip Boosters trading card pack opening simulator.',
        mainTitle: 'Privacy Policy',
        subTitle: 'Legal & Privacy Guidance'
    },
    terms: {
        seoTitle: 'Terms of Service & Cookie Policy - Rip Boosters',
        seoDesc: 'Terms of Service, non-commercial disclaimer, and cookie policies for Rip Boosters.',
        mainTitle: 'Terms of Service',
        subTitle: 'Terms & Cookie Usage'
    },
    contact: {
        seoTitle: 'Contact Us - Rip Boosters',
        seoDesc: 'Get in touch with the Rip Boosters team for feedback, bug reports, or feature requests.',
        mainTitle: 'Contact Us',
        subTitle: 'Support & Feedback Channels'
    }
};