export const STATIC_ROUTES = {
    privacy: {
        seoTitle: "Privacy Policy - Rip Boosters",
        seoDesc: "Privacy Policy and data collection guidelines for Rip Boosters trading card pack opening simulator.",
        mainTitle: "Privacy Policy",
        subTitle: "Data collection and usage details"
    },
    terms: {
        seoTitle: "Terms of Service & Cookies - Rip Boosters",
        seoDesc: "Terms of Service and Cookie Policy for Rip Boosters.",
        mainTitle: "Terms & Cookies",
        subTitle: "Usage terms and technical details"
    },
    contact: {
        seoTitle: "Contact Us - Rip Boosters",
        seoDesc: "Get in touch with the Rip Boosters team for feedback or technical updates.",
        mainTitle: "Contact Us",
        subTitle: "Feedback and support channels"
    }
};

export const SETS_REGISTRY = [
    // -------------------------------------------------------------------------
    // MAGIC: THE GATHERING SETS
    // -------------------------------------------------------------------------
    {
        key: 'mtglea',
        name: 'Limited Edition Alpha',
        category: 'Magic: The Gathering',
        year: '1993',
        publisher: 'Wizards of the Coast',
        totalCards: 295,
        themeColor: '#3a2d1f',
        coverImage: 'card_images/mtg_sets/mtg_alpha_beta_pack_wrapper.jpg',
        isMtg: true,
        aboutTitle: 'About Limited Edition Alpha',
        aboutText: 'The founding set of Magic: The Gathering released in August 1993. Designed by Richard Garfield, Alpha introduced the world to the Power Nine, original Dual Lands, and iconic fantasy spells.',
        seoTitle: 'MTG Alpha Booster Pack Simulator - Rip Boosters',
        seoDesc: 'Open original 1993 Magic: The Gathering Limited Edition Alpha booster packs. Hunt for Black Lotus, Moxes, and Alpha Dual Lands.'
    },
    {
        key: 'mtgleb',
        name: 'Limited Edition Beta',
        category: 'Magic: The Gathering',
        year: '1993',
        publisher: 'Wizards of the Coast',
        totalCards: 302,
        themeColor: '#3a2d1f',
        coverImage: 'card_images/mtg_sets/mtg_alpha_beta_pack_wrapper.jpg',
        isMtg: true,
        aboutTitle: 'About Limited Edition Beta',
        aboutText: 'Released in October 1993 to fix layout errors and missing cards from Alpha, Beta corrected corner radiuses and expanded the print run while preserving the legendary Power Nine.',
        seoTitle: 'MTG Beta Booster Pack Simulator - Rip Boosters',
        seoDesc: 'Rip virtual 1993 MTG Limited Edition Beta booster packs. Test your luck opening Black Lotus, Moxes, and rare Beta Dual Lands.'
    },
    {
        key: 'mtg2ed',
        name: 'Unlimited Edition',
        category: 'Magic: The Gathering',
        year: '1993',
        publisher: 'Wizards of the Coast',
        totalCards: 302,
        themeColor: '#4a3d2f',
        coverImage: 'card_images/mtg_sets/mtg_unlimited_pack_wrapper.jpg',
        isMtg: true,
        aboutTitle: 'About Unlimited Edition',
        aboutText: 'Unlimited marked the first white-bordered reprint print run in MTG history in December 1993, allowing players one final chance to pull original Power Nine cards from boosters.',
        seoTitle: 'MTG Unlimited Booster Pack Simulator - Rip Boosters',
        seoDesc: 'Open white-bordered 1993 MTG Unlimited Edition booster packs online. Pull Black Lotus and white-bordered Dual Lands.'
    },
    {
        key: 'mtgarn',
        name: 'Arabian Nights',
        category: 'Magic: The Gathering',
        year: '1993',
        publisher: 'Wizards of the Coast',
        totalCards: 92,
        themeColor: '#a07830',
        coverImage: 'card_images/mtg_sets/mtg_arn_pack_wrapper.jpg',
        isMtg: true,
        aboutTitle: 'About Arabian Nights',
        aboutText: 'Magic\'s very first expansion set, released in December 1993. Inspired by One Thousand and One Nights, it features iconic staples like Shahrazad, Library of Alexandria, and Bazaar of Baghdad.',
        seoTitle: 'MTG Arabian Nights Booster Simulator - Rip Boosters',
        seoDesc: 'Rip vintage 1993 Arabian Nights MTG booster packs. Pull legendary cards like Library of Alexandria, Bazaar of Baghdad, and Juzám Djinn.'
    },
    {
        key: 'mtgatq',
        name: 'Antiquities',
        category: 'Magic: The Gathering',
        year: '1994',
        publisher: 'Wizards of the Coast',
        totalCards: 100,
        themeColor: '#706050',
        coverImage: 'card_images/mtg_sets/mtg_atq_pack_wrapper.jpg',
        isMtg: true,
        aboutTitle: 'About Antiquities',
        aboutText: 'Released in March 1994, Antiquities explored the tragic lore of the Brothers\' War between Urza and Mishra, introducing powerful artifact-centric strategies and Mishra\'s Workshop.',
        seoTitle: 'MTG Antiquities Booster Pack Simulator - Rip Boosters',
        seoDesc: 'Open 1994 MTG Antiquities booster packs. Hunt for Mishra\'s Workshop, Candelabra of Tawnos, and Urza\'s Power Plant lands.'
    },
    {
        key: 'mtgleg',
        name: 'Legends',
        category: 'Magic: The Gathering',
        year: '1994',
        publisher: 'Wizards of the Coast',
        totalCards: 310,
        themeColor: '#8a2020',
        coverImage: 'card_images/mtg_sets/mtg_leg_pack_wrapper.jpg',
        isMtg: true,
        aboutTitle: 'About Legends',
        aboutText: 'Legends debuted in June 1994, introducing gold multicolor cards, legendary creatures, the commander archetype origins, and powerful Reserve List lands like The Tabernacle at Pendrell Vale.',
        seoTitle: 'MTG Legends Booster Pack Simulator - Rip Boosters',
        seoDesc: 'Rip vintage 1994 Magic: The Gathering Legends booster packs. Chase The Tabernacle at Pendrell Vale, Mana Drain, and Moat.'
    },
    {
        key: 'mtgdrk',
        name: 'The Dark',
        category: 'Magic: The Gathering',
        year: '1994',
        publisher: 'Wizards of the Coast',
        totalCards: 119,
        themeColor: '#2b2b36',
        coverImage: 'card_images/mtg_sets/mtg_drk_pack_wrapper.jpg',
        isMtg: true,
        aboutTitle: 'About The Dark',
        aboutText: 'Released in August 1994, The Dark depicted a post-Brothers\' War era of gloom, desperation, and dangerous magical sacrifice, featuring Blood Moon, Maze of Ith, and Ball Lightning.',
        seoTitle: 'MTG The Dark Booster Pack Simulator - Rip Boosters',
        seoDesc: 'Open 1994 MTG The Dark expansion booster packs. Pull iconic Reserve List cards like Blood Moon, Maze of Ith, and Preacher.'
    },
    {
        key: 'mtg3ed',
        name: 'Revised Edition',
        category: 'Magic: The Gathering',
        year: '1994',
        publisher: 'Wizards of the Coast',
        totalCards: 306,
        themeColor: '#3a2d1f',
        coverImage: 'card_images/mtg_sets/mtg_3ed_revised_pack_wrapper.jpg',
        isMtg: true,
        aboutTitle: 'About Revised Edition',
        aboutText: 'Released in April 1994, Revised Edition updated the core set rulebook and introduced faded white borders, representing the final core set to contain the original 10 Dual Lands.',
        seoTitle: 'MTG Revised Edition Booster Simulator - Rip Boosters',
        seoDesc: 'Open 1994 MTG Revised Edition core booster packs. Hunt for Underground Sea, Volcanic Island, and all 10 original Dual Lands.'
    },
    {
        key: 'rav',
        name: 'Ravnica: City of Guilds',
        category: 'Magic: The Gathering',
        year: '2005',
        publisher: 'Wizards of the Coast',
        totalCards: 306,
        themeColor: '#2c5282',
        coverImage: 'card_images/mtg_sets/mtg_rav_packwrapper4.jpg',
        isMtg: true,
        aboutTitle: 'About Ravnica: City of Guilds',
        aboutText: 'Launched in October 2005, Ravnica introduced the beloved guild system, hybrid mana, and fundamental tournament staples including the iconic original Shock Lands.',
        seoTitle: 'MTG Ravnica City of Guilds Pack Simulator - Rip Boosters',
        seoDesc: 'Open 2005 Ravnica: City of Guilds MTG booster packs. Pull original Shock Lands, Dark Confidant, and Doubling Season.'
    },
    {
        key: 'isd',
        name: 'Innistrad',
        category: 'Magic: The Gathering',
        year: '2011',
        publisher: 'Wizards of the Coast',
        totalCards: 264,
        themeColor: '#4a5568',
        coverImage: 'card_images/mtg_sets/mtg_isd_packwrapper1.jpg',
        isMtg: true,
        aboutTitle: 'About Innistrad',
        aboutText: 'Released in September 2011, Innistrad delivered a acclaimed gothic horror world featuring Vampires, Werewolves, Zombies, double-faced transform cards, and Liliana of the Veil.',
        seoTitle: 'MTG Innistrad Booster Pack Simulator - Rip Boosters',
        seoDesc: 'Rip 2011 MTG Innistrad booster packs online. Hunt for Liliana of the Veil, Snapcaster Mage, and double-faced Werewolf cards.'
    },
    {
        key: 'mtgmsh',
        name: 'Marvel Super Heroes',
        category: 'Magic: The Gathering',
        year: '2026',
        publisher: 'Wizards of the Coast',
        totalCards: 1419,
        themeColor: '#e02424',
        coverImage: 'card_images/mtg_sets/mtg_msh_collectorboosterwrapper.jpg',
        isMtg: true,
        aboutTitle: 'About Marvel Super Heroes',
        aboutText: 'Step into the Marvel Universe featuring iconic heroes, villains, comic panel showcases, and collector booster treatments.',
        seoTitle: 'Marvel Super Heroes Collector Booster Simulator - Rip Boosters',
        seoDesc: 'Open Marvel Super Heroes Magic: The Gathering Collector Boosters. Collect serialized cards, borderless comic art, and source material inserts.'
    },

    // -------------------------------------------------------------------------
    // MARVEL TRADING CARDS
    // -------------------------------------------------------------------------
    {
        key: 'mu1990',
        name: 'Marvel Universe Series 1',
        category: 'Marvel Trading Cards',
        year: '1990',
        publisher: 'Impel',
        totalCards: 167,
        themeColor: '#1a3a8a',
        coverImage: 'card_images/marvel_impel_1990/marvel_impel_1990_packimage2_spiderman.jpg',
        dataFile: './data-mu1990.js',
        dataExport: 'MU1990_DATA',
        isMtg: false,
        aboutTitle: 'About Marvel Universe Series 1 (1990)',
        aboutText: 'The pioneer set that kicked off the 1990s comic trading card boom. Published by Impel in 1990, it features 162 base cards with character power ratings and 5 rare chase Holograms.',
        seoTitle: 'Marvel Universe 1990 Impel Pack Simulator - Rip Boosters',
        seoDesc: 'Open 1990 Impel Marvel Universe Series 1 trading card packs. Hunt for Spider-Man, Wolverine, and rare 3D Hologram insert cards.'
    },
    {
        key: 'mm1992',
        name: 'Marvel Masterpieces 1992',
        category: 'Marvel Trading Cards',
        year: '1992',
        publisher: 'SkyBox',
        totalCards: 105,
        themeColor: '#df9845',
        coverImage: 'card_images/marvel_masterpieces_1992/mm1992_packimage1_wolverine.jpg',
        dataFile: './data-mm1992.js',
        dataExport: 'MM1992_DATA',
        isMtg: false,
        aboutTitle: 'About Marvel Masterpieces (1992)',
        aboutText: 'Illustrated entirely by painted artist Joe Jusko, this premium 100-card base set redefined comic cards with high-gloss stock and 5 ultra-popular etched foil Battle Spectra chase cards.',
        seoTitle: 'Marvel Masterpieces 1992 Pack Simulator - Rip Boosters',
        seoDesc: 'Experience opening 1992 Marvel Masterpieces trading card packs featuring Joe Jusko painted artwork and rare Battle Spectra foil inserts.'
    },
    {
        key: 'xmen1992',
        name: 'The Uncanny X-Men Series 1',
        category: 'Marvel Trading Cards',
        year: '1992',
        publisher: 'Impel',
        totalCards: 105,
        themeColor: '#b8860b',
        coverImage: 'card_images/xmen_impel_1992/uncanny_xmen_1992_packimage2_teal.jpg',
        dataFile: './data-xmen1992.js',
        dataExport: 'XMEN1992_DATA',
        isMtg: false,
        aboutTitle: 'About The Uncanny X-Men Series 1 (1992)',
        aboutText: 'Featuring artwork by legendary comic artist Jim Lee, this 100-card set features iconic X-Men heroes, a 9-card Danger Room puzzle mural, and 5 rare Gold Hologram inserts.',
        seoTitle: '1992 Uncanny X-Men Impel Pack Simulator - Rip Boosters',
        seoDesc: 'Open 1992 Impel Uncanny X-Men Series 1 packs with Jim Lee artwork. Complete the 9-card mural puzzle and collect rare Gold Hologram hits.'
    },
    {
        key: 'mm1993',
        name: 'Marvel Masterpieces 1993',
        category: 'Marvel Trading Cards',
        year: '1993',
        publisher: 'SkyBox',
        totalCards: 98,
        themeColor: '#1a6a1a',
        coverImage: 'card_images/marvel_masterpieces_1993/mm1993_packimage1_silversurfer.jpg',
        dataFile: './data-mm1993.js',
        dataExport: 'MM1993_DATA',
        isMtg: false,
        aboutTitle: 'About Marvel Masterpieces (1993)',
        aboutText: 'Featuring fully painted art by Greg and Tim Hildebrandt, Marvel Masterpieces 1993 expanded on the premium legacy with 90 base cards and 8 textured Dyna-Etch foil insert cards.',
        seoTitle: 'Marvel Masterpieces 1993 Pack Opener - Rip Boosters',
        seoDesc: 'Rip 1993 Marvel Masterpieces booster packs with Hildebrandt Brothers painted card art and Dyna-Etch foil insert hits.'
    },

    // -------------------------------------------------------------------------
    // RETRO 80S CARDS
    // -------------------------------------------------------------------------
    {
        key: 'motu1984',
        name: 'Masters of the Universe',
        category: 'Retro 80s',
        year: '1984',
        publisher: 'Topps',
        totalCards: 110,
        themeColor: '#3a6ea5',
        coverImage: 'card_images/motu_1984/motu1984_packwrapper1.jpg',
        dataFile: './data-motu1984.js',
        dataExport: 'MOTU1984_DATA',
        isMtg: false,
        aboutTitle: 'About Masters of the Universe (1984)',
        aboutText: 'Topps released this classic 88-card base set and 22 sticker insert collection in 1984, capturing iconic scenes and character artwork from the He-Man and the Masters of the Universe animated series.',
        seoTitle: 'He-Man Masters of the Universe 1984 Pack Opener - Rip Boosters',
        seoDesc: 'Rip virtual 1984 Topps Masters of the Universe trading card packs. Complete the 88-card base set, 22 sticker inserts, and interlocking puzzle backs.'
    },
    {
        key: 'gpk1',
        name: 'Garbage Pail Kids Series 1',
        category: 'Retro 80s',
        year: '1985',
        publisher: 'Topps',
        totalCards: 82,
        themeColor: '#df9845',
        coverImage: 'card_images/gpk_series1/gpk_series1_pack_wrapper.jpg',
        dataFile: './data-gpk1.js',
        dataExport: 'GPK1_DATA',
        isMtg: false,
        aboutTitle: 'About Garbage Pail Kids Series 1',
        aboutText: 'Released by Topps in 1985, Series 1 launched the iconic Garbage Pail Kids phenomenon with gross-out parodies of Cabbage Patch Kids created by Art Spiegelman, Mark Newgarden, and John Pound.',
        seoTitle: 'Garbage Pail Kids Series 1 Pack Opener - Rip Boosters',
        seoDesc: 'Open free virtual 1985 Garbage Pail Kids Series 1 booster packs. Collect all 82 original gross-out sticker cards with authentic pull mechanics.'
    }
];